#!/usr/bin/env node
// Generate a precompiled parser from Peggy grammar for faster startup.
const fs = require('fs');
const path = require('path');
const peggy = require('peggy');

const root = process.cwd();
const grammarPath = path.join(root, 'src', 'parser', 'grammar.peggy');
const outPath = path.join(root, 'src', 'parser', 'generated.ts');

try {
  const grammar = fs.readFileSync(grammarPath, 'utf8');
  const source = peggy.generate(grammar, { output: 'source', format: 'es' });
  const banner = `// @ts-nocheck\n// This file is generated by scripts/build-parser.cjs. Do not edit.\n`;
  const wrapped = `${banner}${source}\n`;
  fs.writeFileSync(outPath, wrapped, 'utf8');
  console.log('[icbincss] Generated parser at', path.relative(root, outPath));
} catch (e) {
  console.error('[icbincss] Failed to generate parser:', e && e.message ? e.message : e);
  process.exit(1);
}

